name: flutgpt
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.0
  flutter_chat_ui: ^1.6.6
  get: ^4.6.5
  google_fonts: ^4.0.1
  http: ^0.13.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
